---

- name: Install RabbitMQ server
  ansible.builtin.apt:
    update_cache: "{{ update_apt_cache }}"
    state: present
    name:
      - rabbitmq-server
  tags:
    - packages

- name: Make sure rabbitmq-server is enabled and running
  ansible.builtin.service:
    name: rabbitmq-server
    state: started
    enabled: true
    # TODO: This is likely due to a bug in Ansible.
    # Remove this line in the future.
    # See https://github.com/ansible/ansible/issues/75005
    use: sysvinit

- name: Enable the RabbitMQ Management Console
  community.rabbitmq.rabbitmq_plugin: names=rabbitmq_management state=enabled
  notify: restart rabbitmq-server

- ansible.builtin.import_tasks: setup_vhosts.yml

- ansible.builtin.import_tasks: setup_users.yml
